### ISSUE TITLE
[enhancement] Add ability to share scripts between different controllers

### ISSUE THREAD

**Issue by WiechersV** [imaboldcompany/coffee_controllers-rails#1]
I understand that you can place code that runs on multiple actions of one controller in the init function, but for code that is shared between different controllers.

I might start developing this if it's ok :)

**Comment by dferrazm** [comment]
Hey @WiechersV, never thought about this use case.

Wouldn't this be a case of inheritance? Maybe the shared code could go in a class that would be inherited by other classes.

Take a look http://coffeescript.org/#classes

thanks for the feedback

**Comment by WiechersV** [comment]
This might work. I was thinking that maybe it could follow the rails convention and automatically inherits from the ApplicationController (Where the shared code would reside) if there is one.

You're welcome o/

**Comment by dferrazm** [comment]
Alright. Let us see if more of this scenario comes up again to consider this change.

Thanks!!
